export const TABLE_NAMES = {
  PRODUCT: 'product',
  USER: 'user',
  REVIEW: 'review',
  ROLE: 'role',
  // ASSET_ALLOCATION: 'asset_allocation',
  // ASSET_STATUS: 'asset_status',
  // ASSET_TYPE: 'asset_type',
  // DEPARTMENT: 'department',
  // ORDER: 'order',
  // ORDER_ITEMS: 'order_items',
  // ORDER_STATUS: 'order_status',
  // ROLE: 'role',
  // TICKET: 'ticket',
  // TICKET_ASSET: 'ticket_asset',
  // TICKET_STATUS: 'ticket_status',
  // TICKET_TYPE: 'ticket_type',
  // USER: 'user',
  // TICKET_COMMENT: 'ticket_comment',
  // USER_ROLE: 'user_role',
  // VENDOR: 'vendor',
  // TICKET_IMAGE: 'ticket_images',
  // HISTORY: 'histories',
  // NOTIFICATION: 'notification',
  // LOGIN_HISTORY: 'login_histories',
  // SUB_CATEGORY: 'sub_categories',
  // TICKET_SUB_CATEGORY: 'ticket_sub_categories',
  // CATEGORY: 'category',
  // UNIT_METRICS: 'unit_metrics',
  // END_POINT_SECURITY: 'endPoint_securities',
};
