export enum ROLES {
  BUYER = "BUYER",
  SELLER = "SELLER",
}

export enum PAYMENT_METHODS {
  CREDIT_CARD = "CREDIT_CARD",
  COD = "COD",
  UPI = "UPI",
  BANK_TRANSFER = "BANK_TRANSFER",
  EMI = "EMI",
}

export enum PAYMENT_STATUS {
  PENDING = "PENDING",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
}

export enum ORDER_STATUS {
  PLACED = "PLACED",
  CONFIRMED = "CONFIRMED",
  PROCESSING = "PROCESSING",
  SHIPPED = "SHIPPED",
  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
  DELIVERED = "DELIVERED",
  RETURN_REQUESTED = "RETURN_REQUESTED",
  RETURNED = "RETURNED",
  REFUNDED = "REFUNDED",
  CANCELLED = "CANCELLED",
  FAILED = "FAILED",
}

export enum ASSET_TYPE {
  PRODUCT = "PRODUCT",
  SELLER = "SELLER"
}

export enum SORT_DIRECTION {
  ASC = "ASC",
  DESC = "DESC"
}